const getAllPersonsInKhedma = `SELECT PERSON_DATA.MIL_NO,
KHEDMA_TYPE_NAME,
PERSON_NAME,
DEGREE_NAME,
FEA_NAME,
GROUP_JOB_NAME,
ARMY_JOB_NAME,
COME_IN_DATE, 
PERSON_STATUS_NAME,
TAGNED_AREA_NAME,
MILAD_YEAR,
ID_MARKAZ_CODE,
MILAD_MOSALSL,
PERSON_ADRESS,
MARKAZ_NAME,
MOHAFZA_NAME,
BIRTH_DATE,
DIANA_NAME,
MADANY_NUMBER,
MOAMLA_TYPE_NAME,
ENTQA_ARMY_NAME,
SERV_NAME,
MAJOR_NAME,
SEGEL_NO,
END_JOB_DATE_REALY,
E3FAA_FROM_5EDMA,
MODA_TA5FEED_5EDMA,
HEALTH_LEVEL_NAME,
MRHLA_TXT,
ETEGAH_ELTAWZEE3_NAME,
TAMARKZ_NAME,
IMG_PERSON,
NOTES,
WEAPON_NAME,
TO_UNIT_DATE,
CVD.FIRST_DOSE_DATE,
unit_code.UNIT_NAME
FROM PERSON_DATA LEFT JOIN WEAPON_CODE ON PERSON_DATA.WEAPON_CODE = WEAPON_CODE.WEAPON_CODE 
LEFT JOIN DEGREE_CODE_PERSON ON PERSON_DATA.DEGREE_CODE = DEGREE_CODE_PERSON.DEGREE_CODE 
LEFT JOIN FEA_CODE ON  PERSON_DATA.FEA_CODE = FEA_CODE.FEA_CODE 
LEFT JOIN ARMY_JOB_CODE ON  PERSON_DATA.WORK_TRANING_CODE = ARMY_JOB_CODE.ARMY_JOB_CODE 
LEFT JOIN unit_code  ON PERSON_DATA.UNIT_CODE = unit_code.UNIT_CODE  
LEFT JOIN  KHEDMA_TYPE_CODE ON PERSON_DATA.KHEDMA_TYPE_CODE = KHEDMA_TYPE_CODE.KHEDMA_TYPE_CODE 
LEFT JOIN PERSON_STATUS_CODE ON PERSON_DATA.PERSON_STATUS_CODE = PERSON_STATUS_CODE.PERSON_STATUS_CODE  
LEFT JOIN  TAGNED_AREA_CODE ON  PERSON_DATA.TAGNED_AREA_CODE = TAGNED_AREA_CODE.TAGNED_AREA_CODE 
LEFT JOIN MARKAZ_CODE ON PERSON_DATA.ADD_MARKAZ_CODE = MARKAZ_CODE.MARKAZ_CODE  
LEFT JOIN MOHAFZA_CODE   ON  PERSON_DATA.ADD_MOHAFZA_CODE = MOHAFZA_CODE.MOHAFZA_CODE 
LEFT JOIN  DIANA_CODE ON PERSON_DATA.DIANA_CODE = DIANA_CODE.DIANA_CODE 
LEFT JOIN MOAMLA_TYPE_CODE ON  PERSON_DATA.MOAMLA_TYPE_CODE = MOAMLA_TYPE_CODE.MOAMLA_TYPE_CODE 
LEFT JOIN  ENTQA_ARMY_CODE ON PERSON_DATA.ENTQA_ARMY_CODE = ENTQA_ARMY_CODE.ENTQA_ARMY_CODE 
LEFT JOIN  SERV_CODE ON PERSON_DATA.SERV_CODE = SERV_CODE.SERV_CODE 
LEFT JOIN   MAJOR_CODE ON  PERSON_DATA.MAJOR_CODE = MAJOR_CODE.MAJOR_CODE  
LEFT JOIN MRAHL_TAGNED ON  PERSON_DATA.MRAHEL_ID_BASIC = MRAHL_TAGNED.MRAHEL_ID  
LEFT JOIN HEALTH_LEVEL_CODE ON  PERSON_DATA.HEALTH_LEVEL_CODE = HEALTH_LEVEL_CODE.HEALTH_LEVEL_CODE 
LEFT JOIN  ETEGAH_ELTAWZEE3_CODE ON PERSON_DATA.ETEGAH_ELTAWZEE3_CODE  = ETEGAH_ELTAWZEE3_CODE.ETEGAH_ELTAWZEE3_CODE 
LEFT JOIN  TAMARKZ_CODE ON unit_code.TAMARKZ_CODE = TAMARKZ_CODE.TAMARKZ_CODE 
LEFT JOIN  GROUP_JOBS_CODE ON GROUP_JOBS_CODE.GROUP_JOB_CODE = ARMY_JOB_CODE.GROUP_JOB_CODE 
LEFT JOIN CORONA_VIRUS_DATA CVD ON CVD.MIL_NO = PERSON_DATA.MIL_NO

where 
PERSON_DATA.KHEDMA_TYPE_CODE = 1 And
PERSON_DATA.PERSON_STATUS_CODE = 1 
`


const getSafZabetByMilNo = `
SELECT PERSON_DATA.MIL_NO,
KHEDMA_TYPE_NAME,
PERSON_NAME,
DEGREE_NAME,
FEA_NAME,
GROUP_JOB_NAME,
ARMY_JOB_NAME,
COME_IN_DATE, 
PERSON_STATUS_NAME,
TAGNED_AREA_NAME,
MILAD_YEAR,
ID_MARKAZ_CODE,
MILAD_MOSALSL,
PERSON_ADRESS,
MARKAZ_NAME,
MOHAFZA_NAME,
BIRTH_DATE,
DIANA_NAME,
MADANY_NUMBER,
MOAMLA_TYPE_NAME,
ENTQA_ARMY_NAME,
SERV_NAME,
MAJOR_NAME,
SEGEL_NO,
END_JOB_DATE_REALY,
E3FAA_FROM_5EDMA,
MODA_TA5FEED_5EDMA,
HEALTH_LEVEL_NAME,
MRHLA_TXT,
ETEGAH_ELTAWZEE3_NAME,
TAMARKZ_NAME,
IMG_PERSON,
NOTES,
WEAPON_NAME,
TO_UNIT_DATE,
unit_code.UNIT_NAME,
PERSON_DATA.SUGGESTED_TO_NASHRA
FROM PERSON_DATA LEFT JOIN WEAPON_CODE ON PERSON_DATA.WEAPON_CODE = WEAPON_CODE.WEAPON_CODE 
LEFT JOIN DEGREE_CODE_PERSON ON PERSON_DATA.DEGREE_CODE = DEGREE_CODE_PERSON.DEGREE_CODE 
LEFT JOIN FEA_CODE ON  PERSON_DATA.FEA_CODE = FEA_CODE.FEA_CODE 
LEFT JOIN ARMY_JOB_CODE ON  PERSON_DATA.WORK_TRANING_CODE = ARMY_JOB_CODE.ARMY_JOB_CODE 
LEFT JOIN unit_code  ON PERSON_DATA.UNIT_CODE = unit_code.UNIT_CODE  
LEFT JOIN  KHEDMA_TYPE_CODE ON PERSON_DATA.KHEDMA_TYPE_CODE = KHEDMA_TYPE_CODE.KHEDMA_TYPE_CODE 
LEFT JOIN PERSON_STATUS_CODE ON PERSON_DATA.PERSON_STATUS_CODE = PERSON_STATUS_CODE.PERSON_STATUS_CODE  
LEFT JOIN  TAGNED_AREA_CODE ON  PERSON_DATA.TAGNED_AREA_CODE = TAGNED_AREA_CODE.TAGNED_AREA_CODE 
LEFT JOIN MARKAZ_CODE ON PERSON_DATA.ADD_MARKAZ_CODE = MARKAZ_CODE.MARKAZ_CODE  
LEFT JOIN MOHAFZA_CODE   ON  PERSON_DATA.ADD_MOHAFZA_CODE = MOHAFZA_CODE.MOHAFZA_CODE 
LEFT JOIN  DIANA_CODE ON PERSON_DATA.DIANA_CODE = DIANA_CODE.DIANA_CODE 
LEFT JOIN MOAMLA_TYPE_CODE ON  PERSON_DATA.MOAMLA_TYPE_CODE = MOAMLA_TYPE_CODE.MOAMLA_TYPE_CODE 
LEFT JOIN  ENTQA_ARMY_CODE ON PERSON_DATA.ENTQA_ARMY_CODE = ENTQA_ARMY_CODE.ENTQA_ARMY_CODE 
LEFT JOIN  SERV_CODE ON PERSON_DATA.SERV_CODE = SERV_CODE.SERV_CODE 
LEFT JOIN   MAJOR_CODE ON  PERSON_DATA.MAJOR_CODE = MAJOR_CODE.MAJOR_CODE  
LEFT JOIN MRAHL_TAGNED ON  PERSON_DATA.MRAHEL_ID_BASIC = MRAHL_TAGNED.MRAHEL_ID  
LEFT JOIN HEALTH_LEVEL_CODE ON  PERSON_DATA.HEALTH_LEVEL_CODE = HEALTH_LEVEL_CODE.HEALTH_LEVEL_CODE 
LEFT JOIN  ETEGAH_ELTAWZEE3_CODE ON PERSON_DATA.ETEGAH_ELTAWZEE3_CODE  = ETEGAH_ELTAWZEE3_CODE.ETEGAH_ELTAWZEE3_CODE 
LEFT JOIN  TAMARKZ_CODE ON unit_code.TAMARKZ_CODE = TAMARKZ_CODE.TAMARKZ_CODE 
LEFT JOIN  GROUP_JOBS_CODE ON GROUP_JOBS_CODE.GROUP_JOB_CODE = ARMY_JOB_CODE.GROUP_JOB_CODE 
where 
PERSON_DATA.MIL_NO = '{MIL_NO}' AND
PERSON_DATA.KHEDMA_TYPE_CODE = 1 And
PERSON_DATA.PERSON_STATUS_CODE = 1 
`

const addSafToSuggestedNashra = `
UPDATE PERSON_DATA SET SUGGESTED_TO_NASHRA = 1  WHERE PERSON_DATA.MIL_NO = '{MIL_NO}'
`

const removeSafToSuggestedNashra = `
UPDATE PERSON_DATA SET SUGGESTED_TO_NASHRA = 0  WHERE PERSON_DATA.MIL_NO = '{MIL_NO}'
`

const getAllPersonsInKhedmaWithMainDataOnly = `SELECT PERSON_DATA.MIL_NO,
PERSON_NAME,
DEGREE_NAME,
IMG_PERSON,
unit_code.UNIT_NAME,
ARMY_JOB_NAME,
SUGGESTED_TO_NASHRA
FROM PERSON_DATA 
LEFT JOIN DEGREE_CODE_PERSON ON PERSON_DATA.DEGREE_CODE = DEGREE_CODE_PERSON.DEGREE_CODE 
LEFT JOIN unit_code  ON PERSON_DATA.UNIT_CODE = unit_code.UNIT_CODE
LEFT JOIN ARMY_JOB_CODE ON  PERSON_DATA.WORK_TRANING_CODE = ARMY_JOB_CODE.ARMY_JOB_CODE 
where 
(PERSON_DATA.KHEDMA_TYPE_CODE = 1 And
PERSON_DATA.PERSON_STATUS_CODE = 1) 
OR SUGGESTED_TO_NASHRA = 1
`

const getAllPersonsInKhedmaWithMainDataOnlyByUnitCode = `SELECT PERSON_DATA.MIL_NO,
PERSON_NAME,
DEGREE_NAME,
IMG_PERSON,
unit_code.UNIT_NAME,
ARMY_JOB_NAME,
SUGGESTED_TO_NASHRA
FROM PERSON_DATA 
LEFT JOIN DEGREE_CODE_PERSON ON PERSON_DATA.DEGREE_CODE = DEGREE_CODE_PERSON.DEGREE_CODE 
LEFT JOIN unit_code  ON PERSON_DATA.UNIT_CODE = unit_code.UNIT_CODE
LEFT JOIN ARMY_JOB_CODE ON  PERSON_DATA.WORK_TRANING_CODE = ARMY_JOB_CODE.ARMY_JOB_CODE 
where 
PERSON_DATA.UNIT_CODE = '{UNIT_CODE}' AND
PERSON_DATA.KHEDMA_TYPE_CODE = 1 And
PERSON_DATA.PERSON_STATUS_CODE = 1 
`

const getAllSoldiersInKhedmaWithMainDataOnlyByUnitCode = `
SELECT PERSON_DATA.MIL_NO,
PERSON_NAME,
DEGREE_NAME,
IMG_PERSON,
COME_IN_DATE,
END_JOB_DATE,
unit_code.UNIT_NAME,
ARMY_JOB_NAME,
SERV_NAME,
WAZEFA_IN_UNIT,
TMAM
FROM PERSON_DATA 
LEFT JOIN DEGREE_CODE_PERSON ON PERSON_DATA.DEGREE_CODE = DEGREE_CODE_PERSON.DEGREE_CODE 
LEFT JOIN unit_code  ON PERSON_DATA.UNIT_CODE = unit_code.UNIT_CODE
LEFT JOIN ARMY_JOB_CODE ON  PERSON_DATA.WORK_TRANING_CODE = ARMY_JOB_CODE.ARMY_JOB_CODE 
LEFT JOIN SERV_CODE ON PERSON_DATA.SERV_CODE = SERV_CODE.SERV_CODE
LEFT JOIN MRAHL_TAGNED ON PERSON_DATA.MRAHEL_ID = MRAHL_TAGNED.MRAHEL_ID
where 
PERSON_DATA.UNIT_CODE = '{UNIT_CODE}' AND
PERSON_DATA.KHEDMA_TYPE_CODE = 2 And
PERSON_DATA.PERSON_STATUS_CODE = 1 
`

const getAllUnits = `
select UNIT_CODE, UNIT_NAME, TAMARKZ_NAME from unit_code LEFT join TAMARKZ_CODE ON TAMARKZ_CODE.TAMARKZ_CODE = UNIT_CODE.TAMARKZ_CODE
`

const getSafUnitHistory = `
select t.*,u.UNIT_NAME as UNIT_NAME_FROM ,
(select UNIT_NAME from unit_code
where unit_code.UNIT_CODE = t.UNIT_CODE_TO  ) as UNIT_NAME_TO
from THE_TRANSFER as t Left Join unit_code as u 
ON t.UNIT_CODE_FROM = u.UNIT_CODE
`

const getAllSafwithMinDetails = `
SELECT PERSON_DATA.MIL_NO,
PERSON_NAME,
DEGREE_NAME,
IMG_PERSON,
unit_code.UNIT_NAME,
ARMY_JOB_NAME,
ARMY_JOB_CODE,
SUGGESTED_TO_NASHRA,
UF.UNIT_NAME AS UNIT_FROM,
TCF.TAMARKZ_NAME AS TAMARKOZ_FROM,
UT.UNIT_NAME AS UNIT_TO,
TCT.TAMARKZ_NAME AS TAMARKOZ_TO,
TT.NASHRA_DATE,
TT.TANFEZ_DATE
FROM PERSON_DATA 
LEFT JOIN DEGREE_CODE_PERSON ON PERSON_DATA.DEGREE_CODE = DEGREE_CODE_PERSON.DEGREE_CODE 
LEFT JOIN unit_code  ON PERSON_DATA.UNIT_CODE = unit_code.UNIT_CODE
LEFT JOIN ARMY_JOB_CODE ON  PERSON_DATA.WORK_TRANING_CODE = ARMY_JOB_CODE.ARMY_JOB_CODE 

LEFT JOIN THE_TRANSFER TT ON TT.MIL_NO = PERSON_DATA.MIL_NO 
LEFT JOIN unit_code UF ON UF.UNIT_CODE =  TT.UNIT_CODE_FROM
LEFT JOIN unit_code UT ON UT.UNIT_CODE =  TT.UNIT_CODE_TO
LEFT JOIN TAMARKZ_CODE TCF ON UF.TAMARKZ_CODE = TCF.TAMARKZ_CODE
LEFT JOIN TAMARKZ_CODE TCT ON UT.TAMARKZ_CODE = TCT.TAMARKZ_CODE
where 
((PERSON_DATA.KHEDMA_TYPE_CODE = 1 And
PERSON_DATA.PERSON_STATUS_CODE = 1) 
OR SUGGESTED_TO_NASHRA = 1)
AND  NOT (TT.NASHRA_DATE IS NULL)
ORDER BY MIL_NO
`

const getTa5sosIDByName = `
select * from TA5SES_CODE where NAME = N'{T_NAME}'
`

const getMGEst5damCodeByName = `
select * from MG_EST5DAM_CODE where NAME = N'{MGE_NAME}'
`

const getTypeCodeByName = `
select * from TANK_TYPE_CODE where NAME = N'{TTC_NAME}'
`
const getUnitCodeByName = `
select * from UNIT_CODE where NAME = N'{U_NAME}'
`

const getAllafro3 = `
select FAR3_CODE, FAR3_NAME from FAR3_CODE
`

const setTamamByMilNo = `
update PERSON_DATA tmam='{TMAM}' where MIL_NO = {MIL_NO}
`

module.exports = {
    getAllPersonsInKhedma: getAllPersonsInKhedma,
    getAllPersonsInKhedmaWithMainDataOnly: getAllPersonsInKhedmaWithMainDataOnly,
    getSafZabetByMilNo: getSafZabetByMilNo,
    getAllUnits: getAllUnits,
    addSafToSuggestedNashra: addSafToSuggestedNashra,
    removeSafToSuggestedNashra: removeSafToSuggestedNashra,
    getSafUnitHistory: getSafUnitHistory,
    getAllSafwithMinDetails: getAllSafwithMinDetails,
    getTa5sosIDByName: getTa5sosIDByName,
    getTypeCodeByName: getTypeCodeByName,
    getUnitCodeByName: getUnitCodeByName,
    getAllafro3: getAllafro3,
    setTamamByMilNo: setTamamByMilNo,
    getMGEst5damCodeByName: getMGEst5damCodeByName,
    getAllSoldiersInKhedmaWithMainDataOnlyByUnitCode: getAllSoldiersInKhedmaWithMainDataOnlyByUnitCode,
    getAllPersonsInKhedmaWithMainDataOnlyByUnitCode: getAllPersonsInKhedmaWithMainDataOnlyByUnitCode
}